#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-WebOb
Version  : 1.8.5
Release  : 58
URL      : https://files.pythonhosted.org/packages/9d/1a/0c89c070ee2829c934cb6c7082287c822e28236a4fcf90063e6be7c35532/WebOb-1.8.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/9d/1a/0c89c070ee2829c934cb6c7082287c822e28236a4fcf90063e6be7c35532/WebOb-1.8.5.tar.gz
Summary  : WSGI request and response object
Group    : Development/Tools
License  : MIT
Requires: deprecated-WebOb-license = %{version}-%{release}
Requires: deprecated-WebOb-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools-legacypython
BuildRequires : tox
BuildRequires : virtualenv

%description
WebOb
=====
.. image:: https://travis-ci.org/Pylons/webob.png?branch=master
:target: https://travis-ci.org/Pylons/webob

%package legacypython
Summary: legacypython components for the deprecated-WebOb package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-WebOb package.


%package license
Summary: license components for the deprecated-WebOb package.
Group: Default

%description license
license components for the deprecated-WebOb package.


%package python
Summary: python components for the deprecated-WebOb package.
Group: Default
Provides: deprecated-webob-python

%description python
python components for the deprecated-WebOb package.


%prep
%setup -q -n WebOb-1.8.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554330244
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-WebOb
cp docs/license.txt %{buildroot}/usr/share/package-licenses/deprecated-WebOb/docs_license.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-WebOb/docs_license.txt

%files python
%defattr(-,root,root,-)
